[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "notify-backend-kqueue"
version = "0.1.0"
workspace = ".."

[dependencies]
futures = "0.1.10"
kqueue = "0.2.1"
tempdir = "0.3.5"

[dependencies.notify-backend]
path = "../backend"
