[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "notify-backend-inotify"
version = "0.1.0"

[dependencies]
inotify = "0.5.0"

[dependencies.notify-backend]
path = "../backend"

[dev-dependencies]
tempdir = "0.3.5"
