[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "notify-backend-inotify"
version = "0.1.0"
workspace = ".."

[dependencies]
futures = "0.1.10"
inotify = "0.3.0"
tempdir = "0.3.5"

[dependencies.notify-backend]
path = "../backend"
