[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "notify-backend-poll-tree"
version = "0.1.0"

[dependencies]
futures = "0.1.10"
walkdir = "1.0.7"

[dev-dependencies]
tempdir = "0.3.5"

[dependencies.notify-backend]
path = "../backend"
