[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "notify-backend-poll-tree"
version = "0.1.0"
workspace = ".."

[dependencies]
futures = "0.1.10"
tempdir = "0.3.5"
walkdir = "1.0.7"

[dependencies.notify-backend]
path = "../backend"
