name: CI

on:
  push:
    branches:
      # test & v4 branches
      - 'try-**'
  pull_request:
  release:
    types: [released, pre-released]

jobs:
  ci:
    strategy:
      matrix:
        version:
          - 1.31.1 # MSRV
          - stable
          - nightly
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false # macOS sometimes fails to test
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: setup toolchain
        # `--no-self-update` is needed due to a permission issue on the GHA env.
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.version }} --no-self-update
          rustup override set ${{ matrix.version }}

      - name: MSRV check
        if: matrix.version == '1.31.1'
        shell: bash
        run: |
          mv Cargo.lock.min Cargo.lock
          cargo build

      - name: check build
        if: matrix.version != '1.31.1'
        run: |
          cargo test --no-fail-fast

  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install cargo-audit
        run: |
          rustup override set stable
          cargo install cargo-audit

      - name: audit check
        run: cargo audit
