name: CI

on:
  push:
    branches:
      # test branches
      - 'try-**'

      # main branches
      - main
      - next
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  ci:
    strategy:
      matrix:
        version:
          - 1.59.0 # MSRV
          - stable
          - nightly
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: setup toolchain
        # `--no-self-update` is needed due to a permission issue on the GHA env.
        run: |
          rustup set profile minimal
          rustup toolchain install ${{ matrix.version }} --no-self-update
          rustup override set ${{ matrix.version }}

      - name: check build
        if: matrix.version != 'stable' && matrix.os == 'macos-latest'
        run: cargo check --features=serde,macos_kqueue --examples

      - name: check build
        if: matrix.version != 'stable' && matrix.os != 'macos-latest'
        run: cargo check --features=serde --examples

      - name: check build example
        if: matrix.version != 'stable'
        run: cargo check -p watcher_kind

      - name: test hot_reload_tide
        if: matrix.version != 'stable'
        run: cargo test -p hot_reload_tide

      - name: test
        if: matrix.version == 'stable'
        shell: bash
        run: tests/and-retry --features serde

  bsd:
    strategy:
      matrix:
        target:
          - x86_64-unknown-netbsd
          - x86_64-unknown-freebsd
          - x86_64-apple-darwin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup toolchain
        # `--no-self-update` is needed due to a permission issue on the GHA env.
        run: |
          rustup set profile minimal
          rustup toolchain install stable --no-self-update
          rustup target add ${{ matrix.target}}

      - name: check build
        run: |
          rustc --version && cargo --version  
          cargo build --target ${{ matrix.target}}

  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install cargo-audit
        run: |
          rustup override set stable
          cargo install cargo-audit

      - name: audit check
        run: cargo audit
